// Generated by CoffeeScript 1.3.3
(function() {
  var LogMessage;

  LogMessage = (function() {

    function LogMessage(type, message) {
      this.type = type;
      this.message = message;
    }

    return LogMessage;

  })();

  module.exports = LogMessage;

}).call(this);
